# ruff: noqa: E501
"""Create the PostgreSQL 18 operational schema.

Revision ID: 0001_initial
Revises: None
Created: 2026-08-11

This file is a frozen DDL snapshot. Add a successor migration after release;
never regenerate or import mutable application metadata here.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMA_DDL: tuple[str, ...] = (
    r"""CREATE EXTENSION IF NOT EXISTS pg_trgm;""",
    r"""CREATE TABLE canonical_products (
	id UUID DEFAULT uuidv7() NOT NULL, 
	name TEXT NOT NULL, 
	name_search TEXT GENERATED ALWAYS AS (lower(regexp_replace(normalize(name, NFKC), '[[:punct:][:space:]]+', ' ', 'g'))) STORED, 
	brand TEXT, 
	manufacturer TEXT, 
	quantity NUMERIC(18, 6), 
	unit_of_measure VARCHAR(64), 
	status VARCHAR(32) DEFAULT 'active' NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	CONSTRAINT pk_canonical_products PRIMARY KEY (id), 
	CONSTRAINT ck_canonical_products_status_value CHECK (status IN ('active', 'merged', 'retired')), 
	CONSTRAINT ck_canonical_products_name_length CHECK (length(name) BETWEEN 1 AND 2048), 
	CONSTRAINT ck_canonical_products_quantity_nonnegative CHECK (quantity IS NULL OR quantity >= 0)
);""",
    r"""CREATE TABLE leases (
	resource VARCHAR(512) NOT NULL, 
	owner VARCHAR(256) NOT NULL, 
	lease_token UUID NOT NULL, 
	acquired_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_leases PRIMARY KEY (resource), 
	CONSTRAINT ck_leases_expiry_after_acquisition CHECK (expires_at > acquired_at), 
	CONSTRAINT ck_leases_resource_length CHECK (length(resource) BETWEEN 1 AND 512), 
	CONSTRAINT ck_leases_owner_length CHECK (length(owner) BETWEEN 1 AND 256)
);""",
    r"""CREATE TABLE raw_archive_objects (
	id UUID DEFAULT uuidv7() NOT NULL, 
	content_sha256 VARCHAR(64) NOT NULL, 
	object_key TEXT NOT NULL, 
	content_length BIGINT NOT NULL, 
	archived_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	verified_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_raw_archive_objects PRIMARY KEY (id), 
	CONSTRAINT uq_raw_archive_objects_content_sha256 UNIQUE (content_sha256), 
	CONSTRAINT uq_raw_archive_objects_object_key UNIQUE (object_key), 
	CONSTRAINT ck_raw_archive_objects_content_sha256_format CHECK (content_sha256 ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_raw_archive_objects_content_length_nonnegative CHECK (content_length >= 0)
);""",
    r"""CREATE TABLE retailers (
	id UUID DEFAULT uuidv7() NOT NULL, 
	source_key VARCHAR(128) NOT NULL, 
	legal_name TEXT, 
	display_name TEXT NOT NULL, 
	edi VARCHAR(64), 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	CONSTRAINT pk_retailers PRIMARY KEY (id), 
	CONSTRAINT uq_retailers_source_key UNIQUE (source_key), 
	CONSTRAINT uq_retailers_edi UNIQUE (edi), 
	CONSTRAINT ck_retailers_source_key_length CHECK (length(source_key) BETWEEN 1 AND 128), 
	CONSTRAINT ck_retailers_display_name_length CHECK (length(display_name) BETWEEN 1 AND 512)
);""",
    r"""CREATE TABLE portals (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_id UUID NOT NULL, 
	source_key VARCHAR(128) NOT NULL, 
	family VARCHAR(64) DEFAULT 'custom' NOT NULL, 
	protocol VARCHAR(16) NOT NULL, 
	base_url TEXT, 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	CONSTRAINT pk_portals PRIMARY KEY (id), 
	CONSTRAINT uq_portals_retailer_id_source_key UNIQUE (retailer_id, source_key), 
	CONSTRAINT ck_portals_protocol_value CHECK (protocol IN ('https', 'http', 'ftp', 'ftps', 'fixture')), 
	CONSTRAINT ck_portals_source_key_length CHECK (length(source_key) BETWEEN 1 AND 128), 
	CONSTRAINT fk_portals_retailer_id_retailers FOREIGN KEY(retailer_id) REFERENCES retailers (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE product_identifiers (
	id UUID DEFAULT uuidv7() NOT NULL, 
	product_id UUID NOT NULL, 
	kind VARCHAR(32) NOT NULL, 
	value VARCHAR(128) NOT NULL, 
	normalized_value VARCHAR(128) NOT NULL, 
	issuer_retailer_id UUID, 
	is_validated BOOLEAN DEFAULT false NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	CONSTRAINT pk_product_identifiers PRIMARY KEY (id), 
	CONSTRAINT ck_product_identifiers_kind_value CHECK (kind IN ('gtin', 'retailer_item', 'manufacturer', 'unknown')), 
	CONSTRAINT ck_product_identifiers_normalized_value_length CHECK (length(normalized_value) BETWEEN 1 AND 128), 
	CONSTRAINT fk_product_identifiers_product_id_canonical_products FOREIGN KEY(product_id) REFERENCES canonical_products (id) ON DELETE CASCADE, 
	CONSTRAINT fk_product_identifiers_issuer_retailer_id_retailers FOREIGN KEY(issuer_retailer_id) REFERENCES retailers (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE source_files (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_id UUID NOT NULL, 
	portal_id UUID NOT NULL, 
	remote_id TEXT NOT NULL, 
	download_url TEXT NOT NULL, 
	original_filename TEXT NOT NULL, 
	document_type VARCHAR(32) NOT NULL, 
	compression VARCHAR(16) NOT NULL, 
	protocol VARCHAR(16) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	discovered_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	source_timestamp TIMESTAMP WITH TIME ZONE, 
	declared_content_length BIGINT, 
	media_type TEXT, 
	etag TEXT, 
	last_modified TIMESTAMP WITH TIME ZONE, 
	response_metadata JSONB DEFAULT '[]'::jsonb NOT NULL, 
	raw_archive_object_id UUID, 
	parser_version VARCHAR(128), 
	download_started_at TIMESTAMP WITH TIME ZONE, 
	download_finished_at TIMESTAMP WITH TIME ZONE, 
	download_status_code INTEGER, 
	download_content_length BIGINT, 
	download_response_metadata JSONB, 
	error_code VARCHAR(128), 
	error_message TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	CONSTRAINT pk_source_files PRIMARY KEY (id), 
	CONSTRAINT uq_source_files_portal_id_remote_id UNIQUE (portal_id, remote_id), 
	CONSTRAINT ck_source_files_document_type_value CHECK (document_type IN ('stores', 'price_full', 'price_delta', 'promotion_full', 'promotion_delta', 'unknown')), 
	CONSTRAINT ck_source_files_compression_value CHECK (compression IN ('none', 'gzip', 'zip', 'zstandard', 'unknown')), 
	CONSTRAINT ck_source_files_protocol_value CHECK (protocol IN ('https', 'http', 'ftp', 'ftps', 'fixture')), 
	CONSTRAINT ck_source_files_status_value CHECK (status IN ('discovered', 'downloading', 'archived', 'parsing', 'staged', 'validating', 'applying', 'completed', 'quarantined', 'failed_retryable', 'failed_terminal')), 
	CONSTRAINT ck_source_files_remote_id_length CHECK (length(remote_id) BETWEEN 1 AND 4096), 
	CONSTRAINT ck_source_files_original_filename_length CHECK (length(original_filename) BETWEEN 1 AND 2048), 
	CONSTRAINT ck_source_files_declared_content_length_nonnegative CHECK (declared_content_length IS NULL OR declared_content_length >= 0), 
	CONSTRAINT ck_source_files_download_content_length_nonnegative CHECK (download_content_length IS NULL OR download_content_length >= 0), 
	CONSTRAINT ck_source_files_download_status_code_range CHECK (download_status_code IS NULL OR download_status_code BETWEEN 100 AND 599), 
	CONSTRAINT ck_source_files_download_time_order CHECK (download_finished_at IS NULL OR download_started_at IS NULL OR download_finished_at >= download_started_at), 
	CONSTRAINT fk_source_files_retailer_id_retailers FOREIGN KEY(retailer_id) REFERENCES retailers (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_source_files_portal_id_portals FOREIGN KEY(portal_id) REFERENCES portals (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_source_files_raw_archive_object_id_raw_archive_objects FOREIGN KEY(raw_archive_object_id) REFERENCES raw_archive_objects (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE applied_source_contents (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_id UUID NOT NULL, 
	document_type VARCHAR(32) NOT NULL, 
	content_sha256 VARCHAR(64) NOT NULL, 
	source_file_id UUID NOT NULL, 
	applied_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	CONSTRAINT pk_applied_source_contents PRIMARY KEY (id), 
	CONSTRAINT uq_applied_source_contents_retailer_id_document_type_co_7fc6 UNIQUE (retailer_id, document_type, content_sha256), 
	CONSTRAINT uq_applied_source_contents_source_file_id UNIQUE (source_file_id), 
	CONSTRAINT ck_applied_source_contents_document_type_value CHECK (document_type IN ('stores', 'price_full', 'price_delta', 'promotion_full', 'promotion_delta', 'unknown')), 
	CONSTRAINT ck_applied_source_contents_content_sha256_format CHECK (content_sha256 ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT fk_applied_source_contents_retailer_id_retailers FOREIGN KEY(retailer_id) REFERENCES retailers (id) ON DELETE RESTRICT, 
	CONSTRAINT fk_applied_source_contents_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE ingestion_runs (
	id UUID DEFAULT uuidv7() NOT NULL, 
	source_file_id UUID NOT NULL, 
	attempt INTEGER NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	metadata_records BIGINT DEFAULT 0 NOT NULL, 
	store_records BIGINT DEFAULT 0 NOT NULL, 
	price_records BIGINT DEFAULT 0 NOT NULL, 
	promotion_records BIGINT DEFAULT 0 NOT NULL, 
	warnings BIGINT DEFAULT 0 NOT NULL, 
	rejected_records BIGINT DEFAULT 0 NOT NULL, 
	inserted_records BIGINT DEFAULT 0 NOT NULL, 
	updated_records BIGINT DEFAULT 0 NOT NULL, 
	unchanged_records BIGINT DEFAULT 0 NOT NULL, 
	unavailable_records BIGINT DEFAULT 0 NOT NULL, 
	history_events BIGINT DEFAULT 0 NOT NULL, 
	error_code VARCHAR(128), 
	error_message TEXT, 
	CONSTRAINT pk_ingestion_runs PRIMARY KEY (id), 
	CONSTRAINT uq_ingestion_runs_source_file_id_attempt UNIQUE (source_file_id, attempt), 
	CONSTRAINT ck_ingestion_runs_status_value CHECK (status IN ('discovered', 'downloading', 'archived', 'parsing', 'staged', 'validating', 'applying', 'completed', 'quarantined', 'failed_retryable', 'failed_terminal')), 
	CONSTRAINT ck_ingestion_runs_attempt_positive CHECK (attempt > 0), 
	CONSTRAINT ck_ingestion_runs_run_time_order CHECK (finished_at IS NULL OR finished_at >= started_at), 
	CONSTRAINT ck_ingestion_runs_counts_nonnegative CHECK (metadata_records >= 0 AND store_records >= 0 AND price_records >= 0 AND promotion_records >= 0 AND warnings >= 0 AND rejected_records >= 0 AND inserted_records >= 0 AND updated_records >= 0 AND unchanged_records >= 0 AND unavailable_records >= 0 AND history_events >= 0), 
	CONSTRAINT fk_ingestion_runs_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE promotions (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_id UUID NOT NULL, 
	source_promotion_id VARCHAR(256) NOT NULL, 
	source_scope_store_code VARCHAR(128) DEFAULT '' NOT NULL, 
	description TEXT, 
	discount_kind VARCHAR(32) NOT NULL, 
	starts_at TIMESTAMP WITH TIME ZONE, 
	ends_at TIMESTAMP WITH TIME ZONE, 
	reward_type INTEGER, 
	allows_multiple_discounts BOOLEAN, 
	minimum_quantity NUMERIC(18, 6), 
	maximum_quantity NUMERIC(18, 6), 
	discount_rate NUMERIC(10, 6), 
	minimum_purchase NUMERIC(14, 4), 
	discounted_price NUMERIC(14, 4), 
	discounted_unit_price NUMERIC(14, 4), 
	minimum_items_offered INTEGER, 
	additional_restrictions TEXT, 
	remarks TEXT, 
	is_active BOOLEAN, 
	fingerprint_sha256 VARCHAR(64) NOT NULL, 
	source_file_id UUID NOT NULL, 
	valid_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	valid_to TIMESTAMP WITH TIME ZONE, 
	last_observed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_promotions PRIMARY KEY (id), 
	CONSTRAINT ck_promotions_discount_kind_value CHECK (discount_kind IN ('fixed_price', 'percentage', 'amount', 'quantity', 'second_item', 'mix_and_match', 'conditional', 'unknown')), 
	CONSTRAINT ck_promotions_fingerprint_format CHECK (fingerprint_sha256 ~ '^[0-9a-f]{64}$'), 
	CONSTRAINT ck_promotions_validity_order CHECK (valid_to IS NULL OR valid_to > valid_from), 
	CONSTRAINT ck_promotions_source_time_order CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at), 
	CONSTRAINT ck_promotions_minimum_quantity_nonnegative CHECK (minimum_quantity IS NULL OR minimum_quantity >= 0), 
	CONSTRAINT ck_promotions_maximum_quantity_nonnegative CHECK (maximum_quantity IS NULL OR maximum_quantity >= 0), 
	CONSTRAINT ck_promotions_quantity_range CHECK (maximum_quantity IS NULL OR minimum_quantity IS NULL OR maximum_quantity >= minimum_quantity), 
	CONSTRAINT ck_promotions_discount_rate_nonnegative CHECK (discount_rate IS NULL OR discount_rate >= 0), 
	CONSTRAINT ck_promotions_minimum_purchase_nonnegative CHECK (minimum_purchase IS NULL OR minimum_purchase >= 0), 
	CONSTRAINT ck_promotions_discounted_price_nonnegative CHECK (discounted_price IS NULL OR discounted_price >= 0), 
	CONSTRAINT ck_promotions_discounted_unit_price_nonnegative CHECK (discounted_unit_price IS NULL OR discounted_unit_price >= 0), 
	CONSTRAINT ck_promotions_minimum_items_nonnegative CHECK (minimum_items_offered IS NULL OR minimum_items_offered >= 0), 
	CONSTRAINT fk_promotions_retailer_id_retailers FOREIGN KEY(retailer_id) REFERENCES retailers (id) ON DELETE CASCADE, 
	CONSTRAINT fk_promotions_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE replay_runs (
	id UUID DEFAULT uuidv7() NOT NULL, 
	source_file_id UUID NOT NULL, 
	requested_parser_version VARCHAR(128) NOT NULL, 
	previous_parser_version VARCHAR(128), 
	status VARCHAR(32) NOT NULL, 
	started_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	finished_at TIMESTAMP WITH TIME ZONE, 
	result_summary JSONB, 
	error_message TEXT, 
	CONSTRAINT pk_replay_runs PRIMARY KEY (id), 
	CONSTRAINT ck_replay_runs_status_value CHECK (status IN ('discovered', 'downloading', 'archived', 'parsing', 'staged', 'validating', 'applying', 'completed', 'quarantined', 'failed_retryable', 'failed_terminal')), 
	CONSTRAINT ck_replay_runs_run_time_order CHECK (finished_at IS NULL OR finished_at >= started_at), 
	CONSTRAINT fk_replay_runs_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE retailer_items (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_id UUID NOT NULL, 
	source_item_code VARCHAR(128) NOT NULL, 
	gtin VARCHAR(14), 
	item_type INTEGER, 
	name TEXT NOT NULL, 
	name_search TEXT GENERATED ALWAYS AS (lower(regexp_replace(normalize(name, NFKC), '[[:punct:][:space:]]+', ' ', 'g'))) STORED, 
	manufacturer_name TEXT, 
	manufacturer_country TEXT, 
	manufacturer_description TEXT, 
	unit_quantity TEXT, 
	quantity NUMERIC(18, 6), 
	unit_of_measure VARCHAR(64), 
	is_weighted BOOLEAN, 
	quantity_in_package NUMERIC(18, 6), 
	first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_source_file_id UUID NOT NULL, 
	CONSTRAINT pk_retailer_items PRIMARY KEY (id), 
	CONSTRAINT uq_retailer_items_retailer_id_source_item_code UNIQUE (retailer_id, source_item_code), 
	CONSTRAINT ck_retailer_items_source_item_code_length CHECK (length(source_item_code) BETWEEN 1 AND 128), 
	CONSTRAINT ck_retailer_items_name_length CHECK (length(name) BETWEEN 1 AND 2048), 
	CONSTRAINT ck_retailer_items_gtin_digits CHECK (gtin IS NULL OR gtin ~ '^[0-9]{8,14}$'), 
	CONSTRAINT ck_retailer_items_quantity_nonnegative CHECK (quantity IS NULL OR quantity >= 0), 
	CONSTRAINT ck_retailer_items_package_quantity_nonnegative CHECK (quantity_in_package IS NULL OR quantity_in_package >= 0), 
	CONSTRAINT ck_retailer_items_seen_time_order CHECK (last_seen_at >= first_seen_at), 
	CONSTRAINT fk_retailer_items_retailer_id_retailers FOREIGN KEY(retailer_id) REFERENCES retailers (id) ON DELETE CASCADE, 
	CONSTRAINT fk_retailer_items_last_source_file_id_source_files FOREIGN KEY(last_source_file_id) REFERENCES source_files (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE staged_documents (
	source_file_id UUID NOT NULL, 
	metadata_index INTEGER NOT NULL, 
	document_type VARCHAR(32) NOT NULL, 
	chain_id VARCHAR(128), 
	subchain_id VARCHAR(128), 
	store_id VARCHAR(128), 
	audit_number VARCHAR(128), 
	source_updated_at TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_staged_documents PRIMARY KEY (source_file_id, metadata_index), 
	CONSTRAINT ck_staged_documents_document_type_value CHECK (document_type IN ('stores', 'price_full', 'price_delta', 'promotion_full', 'promotion_delta', 'unknown')), 
	CONSTRAINT fk_staged_documents_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE staged_prices (
	source_file_id UUID NOT NULL, 
	record_index BIGINT NOT NULL, 
	chain_id VARCHAR(128) NOT NULL, 
	subchain_id VARCHAR(128) NOT NULL, 
	source_store_id VARCHAR(128) NOT NULL, 
	source_item_code VARCHAR(128) NOT NULL, 
	gtin VARCHAR(14), 
	item_type INTEGER, 
	item_name TEXT NOT NULL, 
	manufacturer_name TEXT, 
	manufacturer_country TEXT, 
	manufacturer_description TEXT, 
	unit_quantity TEXT, 
	quantity NUMERIC(18, 6), 
	unit_of_measure VARCHAR(64), 
	is_weighted BOOLEAN, 
	quantity_in_package NUMERIC(18, 6), 
	item_price NUMERIC(14, 4) NOT NULL, 
	unit_of_measure_price NUMERIC(14, 4), 
	allow_discount BOOLEAN, 
	item_status INTEGER, 
	price_updated_at TIMESTAMP WITH TIME ZONE, 
	last_sale_at TIMESTAMP WITH TIME ZONE, 
	audit_number VARCHAR(128), 
	CONSTRAINT pk_staged_prices PRIMARY KEY (source_file_id, record_index), 
	CONSTRAINT ck_staged_prices_item_price_nonnegative CHECK (item_price >= 0), 
	CONSTRAINT ck_staged_prices_unit_price_nonnegative CHECK (unit_of_measure_price IS NULL OR unit_of_measure_price >= 0), 
	CONSTRAINT ck_staged_prices_quantity_nonnegative CHECK (quantity IS NULL OR quantity >= 0), 
	CONSTRAINT ck_staged_prices_package_quantity_nonnegative CHECK (quantity_in_package IS NULL OR quantity_in_package >= 0), 
	CONSTRAINT fk_staged_prices_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE staged_promotions (
	source_file_id UUID NOT NULL, 
	record_index BIGINT NOT NULL, 
	chain_id VARCHAR(128) NOT NULL, 
	subchain_id VARCHAR(128) NOT NULL, 
	source_scope_store_code VARCHAR(128) NOT NULL, 
	source_promotion_id VARCHAR(256) NOT NULL, 
	description TEXT, 
	discount_kind VARCHAR(32) NOT NULL, 
	starts_at TIMESTAMP WITH TIME ZONE, 
	ends_at TIMESTAMP WITH TIME ZONE, 
	reward_type INTEGER, 
	allows_multiple_discounts BOOLEAN, 
	minimum_quantity NUMERIC(18, 6), 
	maximum_quantity NUMERIC(18, 6), 
	discount_rate NUMERIC(10, 6), 
	minimum_purchase NUMERIC(14, 4), 
	discounted_price NUMERIC(14, 4), 
	discounted_unit_price NUMERIC(14, 4), 
	minimum_items_offered INTEGER, 
	additional_restrictions TEXT, 
	remarks TEXT, 
	is_active BOOLEAN, 
	fingerprint_sha256 VARCHAR(64) NOT NULL, 
	CONSTRAINT pk_staged_promotions PRIMARY KEY (source_file_id, record_index), 
	CONSTRAINT ck_staged_promotions_discount_kind_value CHECK (discount_kind IN ('fixed_price', 'percentage', 'amount', 'quantity', 'second_item', 'mix_and_match', 'conditional', 'unknown')), 
	CONSTRAINT fk_staged_promotions_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE staged_stores (
	source_file_id UUID NOT NULL, 
	record_index BIGINT NOT NULL, 
	chain_id VARCHAR(128) NOT NULL, 
	subchain_id VARCHAR(128) NOT NULL, 
	source_store_id VARCHAR(128) NOT NULL, 
	audit_number VARCHAR(128), 
	store_type VARCHAR(128), 
	chain_name TEXT, 
	subchain_name TEXT, 
	store_name TEXT NOT NULL, 
	address TEXT, 
	city TEXT, 
	postal_code VARCHAR(32), 
	CONSTRAINT pk_staged_stores PRIMARY KEY (source_file_id, record_index), 
	CONSTRAINT fk_staged_stores_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE stores (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_id UUID NOT NULL, 
	chain_code VARCHAR(128) NOT NULL, 
	subchain_code VARCHAR(128) DEFAULT '' NOT NULL, 
	source_store_code VARCHAR(128) NOT NULL, 
	audit_number VARCHAR(128), 
	store_type VARCHAR(128), 
	chain_name TEXT, 
	subchain_name TEXT, 
	name TEXT NOT NULL, 
	name_search TEXT GENERATED ALWAYS AS (lower(regexp_replace(normalize(name, NFKC), '[[:punct:][:space:]]+', ' ', 'g'))) STORED, 
	address TEXT, 
	city TEXT, 
	postal_code VARCHAR(32), 
	is_active BOOLEAN DEFAULT true NOT NULL, 
	first_seen_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	last_source_file_id UUID, 
	CONSTRAINT pk_stores PRIMARY KEY (id), 
	CONSTRAINT uq_stores_retailer_id_subchain_code_source_store_code UNIQUE (retailer_id, subchain_code, source_store_code), 
	CONSTRAINT ck_stores_chain_code_length CHECK (length(chain_code) BETWEEN 1 AND 128), 
	CONSTRAINT ck_stores_source_store_code_length CHECK (length(source_store_code) BETWEEN 1 AND 128), 
	CONSTRAINT ck_stores_name_length CHECK (length(name) BETWEEN 1 AND 1024), 
	CONSTRAINT ck_stores_seen_time_order CHECK (last_seen_at >= first_seen_at), 
	CONSTRAINT fk_stores_retailer_id_retailers FOREIGN KEY(retailer_id) REFERENCES retailers (id) ON DELETE CASCADE, 
	CONSTRAINT fk_stores_last_source_file_id_source_files FOREIGN KEY(last_source_file_id) REFERENCES source_files (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE availability_history (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_item_id UUID NOT NULL, 
	store_id UUID NOT NULL, 
	is_available BOOLEAN NOT NULL, 
	item_status INTEGER, 
	source_file_id UUID NOT NULL, 
	valid_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	valid_to TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_availability_history PRIMARY KEY (id), 
	CONSTRAINT ck_availability_history_validity_order CHECK (valid_to IS NULL OR valid_to > valid_from), 
	CONSTRAINT fk_availability_history_retailer_item_id_retailer_items FOREIGN KEY(retailer_item_id) REFERENCES retailer_items (id) ON DELETE CASCADE, 
	CONSTRAINT fk_availability_history_store_id_stores FOREIGN KEY(store_id) REFERENCES stores (id) ON DELETE CASCADE, 
	CONSTRAINT fk_availability_history_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE confirmed_product_matches (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_item_id UUID NOT NULL, 
	canonical_product_id UUID NOT NULL, 
	method VARCHAR(64) NOT NULL, 
	evidence JSONB DEFAULT '{}'::jsonb NOT NULL, 
	confirmed_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	confirmed_by TEXT NOT NULL, 
	CONSTRAINT pk_confirmed_product_matches PRIMARY KEY (id), 
	CONSTRAINT uq_confirmed_product_matches_retailer_item_id UNIQUE (retailer_item_id), 
	CONSTRAINT fk_confirmed_product_matches_retailer_item_id_retailer_items FOREIGN KEY(retailer_item_id) REFERENCES retailer_items (id) ON DELETE CASCADE, 
	CONSTRAINT fk_confirmed_product_matches_canonical_product_id_canon_6ea3 FOREIGN KEY(canonical_product_id) REFERENCES canonical_products (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE current_availability (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_item_id UUID NOT NULL, 
	store_id UUID NOT NULL, 
	is_available BOOLEAN NOT NULL, 
	item_status INTEGER, 
	source_file_id UUID NOT NULL, 
	first_observed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_observed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_current_availability PRIMARY KEY (id), 
	CONSTRAINT uq_current_availability_retailer_item_id_store_id UNIQUE (retailer_item_id, store_id), 
	CONSTRAINT ck_current_availability_observation_time_order CHECK (last_observed_at >= first_observed_at), 
	CONSTRAINT fk_current_availability_retailer_item_id_retailer_items FOREIGN KEY(retailer_item_id) REFERENCES retailer_items (id) ON DELETE CASCADE, 
	CONSTRAINT fk_current_availability_store_id_stores FOREIGN KEY(store_id) REFERENCES stores (id) ON DELETE CASCADE, 
	CONSTRAINT fk_current_availability_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE current_prices (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_item_id UUID NOT NULL, 
	store_id UUID NOT NULL, 
	item_price NUMERIC(14, 4) NOT NULL, 
	unit_of_measure_price NUMERIC(14, 4), 
	allow_discount BOOLEAN, 
	source_updated_at TIMESTAMP WITH TIME ZONE, 
	last_sale_at TIMESTAMP WITH TIME ZONE, 
	audit_number VARCHAR(128), 
	source_file_id UUID NOT NULL, 
	first_observed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_observed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_current_prices PRIMARY KEY (id), 
	CONSTRAINT uq_current_prices_retailer_item_id_store_id UNIQUE (retailer_item_id, store_id), 
	CONSTRAINT ck_current_prices_item_price_nonnegative CHECK (item_price >= 0), 
	CONSTRAINT ck_current_prices_unit_price_nonnegative CHECK (unit_of_measure_price IS NULL OR unit_of_measure_price >= 0), 
	CONSTRAINT ck_current_prices_observation_time_order CHECK (last_observed_at >= first_observed_at), 
	CONSTRAINT fk_current_prices_retailer_item_id_retailer_items FOREIGN KEY(retailer_item_id) REFERENCES retailer_items (id) ON DELETE CASCADE, 
	CONSTRAINT fk_current_prices_store_id_stores FOREIGN KEY(store_id) REFERENCES stores (id) ON DELETE CASCADE, 
	CONSTRAINT fk_current_prices_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE price_history (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_item_id UUID NOT NULL, 
	store_id UUID NOT NULL, 
	item_price NUMERIC(14, 4) NOT NULL, 
	unit_of_measure_price NUMERIC(14, 4), 
	allow_discount BOOLEAN, 
	source_updated_at TIMESTAMP WITH TIME ZONE, 
	last_sale_at TIMESTAMP WITH TIME ZONE, 
	audit_number VARCHAR(128), 
	source_file_id UUID NOT NULL, 
	valid_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	valid_to TIMESTAMP WITH TIME ZONE, 
	CONSTRAINT pk_price_history PRIMARY KEY (id), 
	CONSTRAINT ck_price_history_validity_order CHECK (valid_to IS NULL OR valid_to > valid_from), 
	CONSTRAINT ck_price_history_item_price_nonnegative CHECK (item_price >= 0), 
	CONSTRAINT ck_price_history_unit_price_nonnegative CHECK (unit_of_measure_price IS NULL OR unit_of_measure_price >= 0), 
	CONSTRAINT fk_price_history_retailer_item_id_retailer_items FOREIGN KEY(retailer_item_id) REFERENCES retailer_items (id) ON DELETE CASCADE, 
	CONSTRAINT fk_price_history_store_id_stores FOREIGN KEY(store_id) REFERENCES stores (id) ON DELETE CASCADE, 
	CONSTRAINT fk_price_history_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE RESTRICT
);""",
    r"""CREATE TABLE product_match_candidates (
	id UUID DEFAULT uuidv7() NOT NULL, 
	retailer_item_id UUID NOT NULL, 
	canonical_product_id UUID NOT NULL, 
	method VARCHAR(64) NOT NULL, 
	score NUMERIC(8, 7) NOT NULL, 
	status VARCHAR(32) DEFAULT 'pending' NOT NULL, 
	evidence JSONB DEFAULT '{}'::jsonb NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	reviewed_at TIMESTAMP WITH TIME ZONE, 
	reviewed_by TEXT, 
	CONSTRAINT pk_product_match_candidates PRIMARY KEY (id), 
	CONSTRAINT uq_product_match_candidates_retailer_item_id_canonical__b150 UNIQUE (retailer_item_id, canonical_product_id, method), 
	CONSTRAINT ck_product_match_candidates_status_value CHECK (status IN ('pending', 'accepted', 'rejected', 'superseded')), 
	CONSTRAINT ck_product_match_candidates_score_range CHECK (score BETWEEN 0 AND 1), 
	CONSTRAINT fk_product_match_candidates_retailer_item_id_retailer_items FOREIGN KEY(retailer_item_id) REFERENCES retailer_items (id) ON DELETE CASCADE, 
	CONSTRAINT fk_product_match_candidates_canonical_product_id_canoni_e360 FOREIGN KEY(canonical_product_id) REFERENCES canonical_products (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE promotion_clubs (
	promotion_id UUID NOT NULL, 
	club_id VARCHAR(128) NOT NULL, 
	CONSTRAINT pk_promotion_clubs PRIMARY KEY (promotion_id, club_id), 
	CONSTRAINT fk_promotion_clubs_promotion_id_promotions FOREIGN KEY(promotion_id) REFERENCES promotions (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE promotion_items (
	promotion_id UUID NOT NULL, 
	retailer_item_id UUID NOT NULL, 
	item_type INTEGER, 
	is_gift BOOLEAN DEFAULT false NOT NULL, 
	CONSTRAINT pk_promotion_items PRIMARY KEY (promotion_id, retailer_item_id), 
	CONSTRAINT fk_promotion_items_promotion_id_promotions FOREIGN KEY(promotion_id) REFERENCES promotions (id) ON DELETE CASCADE, 
	CONSTRAINT fk_promotion_items_retailer_item_id_retailer_items FOREIGN KEY(retailer_item_id) REFERENCES retailer_items (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE promotion_stores (
	promotion_id UUID NOT NULL, 
	store_id UUID NOT NULL, 
	CONSTRAINT pk_promotion_stores PRIMARY KEY (promotion_id, store_id), 
	CONSTRAINT fk_promotion_stores_promotion_id_promotions FOREIGN KEY(promotion_id) REFERENCES promotions (id) ON DELETE CASCADE, 
	CONSTRAINT fk_promotion_stores_store_id_stores FOREIGN KEY(store_id) REFERENCES stores (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE source_file_events (
	id UUID DEFAULT uuidv7() NOT NULL, 
	source_file_id UUID NOT NULL, 
	ingestion_run_id UUID NOT NULL, 
	from_status VARCHAR(32), 
	to_status VARCHAR(32) NOT NULL, 
	error_code VARCHAR(128), 
	error_message TEXT, 
	occurred_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	CONSTRAINT pk_source_file_events PRIMARY KEY (id), 
	CONSTRAINT ck_source_file_events_from_status_value CHECK (from_status IN ('discovered', 'downloading', 'archived', 'parsing', 'staged', 'validating', 'applying', 'completed', 'quarantined', 'failed_retryable', 'failed_terminal')), 
	CONSTRAINT ck_source_file_events_to_status_value CHECK (to_status IN ('discovered', 'downloading', 'archived', 'parsing', 'staged', 'validating', 'applying', 'completed', 'quarantined', 'failed_retryable', 'failed_terminal')), 
	CONSTRAINT fk_source_file_events_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE CASCADE, 
	CONSTRAINT fk_source_file_events_ingestion_run_id_ingestion_runs FOREIGN KEY(ingestion_run_id) REFERENCES ingestion_runs (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE staged_promotion_clubs (
	source_file_id UUID NOT NULL, 
	record_index BIGINT NOT NULL, 
	club_index INTEGER NOT NULL, 
	club_id VARCHAR(128) NOT NULL, 
	CONSTRAINT pk_staged_promotion_clubs PRIMARY KEY (source_file_id, record_index, club_index), 
	CONSTRAINT fk_staged_promotion_clubs_source_file_id_record_index_s_cece FOREIGN KEY(source_file_id, record_index) REFERENCES staged_promotions (source_file_id, record_index) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);""",
    r"""CREATE TABLE staged_promotion_items (
	source_file_id UUID NOT NULL, 
	record_index BIGINT NOT NULL, 
	item_index INTEGER NOT NULL, 
	source_item_code VARCHAR(128) NOT NULL, 
	item_type INTEGER, 
	is_gift BOOLEAN NOT NULL, 
	CONSTRAINT pk_staged_promotion_items PRIMARY KEY (source_file_id, record_index, item_index), 
	CONSTRAINT fk_staged_promotion_items_source_file_id_record_index_s_d187 FOREIGN KEY(source_file_id, record_index) REFERENCES staged_promotions (source_file_id, record_index) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);""",
    r"""CREATE TABLE staged_promotion_stores (
	source_file_id UUID NOT NULL, 
	record_index BIGINT NOT NULL, 
	store_index INTEGER NOT NULL, 
	source_store_code VARCHAR(128) NOT NULL, 
	CONSTRAINT pk_staged_promotion_stores PRIMARY KEY (source_file_id, record_index, store_index), 
	CONSTRAINT fk_staged_promotion_stores_source_file_id_record_index__86a1 FOREIGN KEY(source_file_id, record_index) REFERENCES staged_promotions (source_file_id, record_index) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);""",
    r"""CREATE TABLE store_aliases (
	id UUID DEFAULT uuidv7() NOT NULL, 
	store_id UUID NOT NULL, 
	retailer_id UUID NOT NULL, 
	alias_kind VARCHAR(32) NOT NULL, 
	alias_value VARCHAR(256) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	CONSTRAINT pk_store_aliases PRIMARY KEY (id), 
	CONSTRAINT uq_store_aliases_retailer_id_alias_kind_alias_value UNIQUE (retailer_id, alias_kind, alias_value), 
	CONSTRAINT ck_store_aliases_alias_value_length CHECK (length(alias_value) BETWEEN 1 AND 256), 
	CONSTRAINT fk_store_aliases_store_id_stores FOREIGN KEY(store_id) REFERENCES stores (id) ON DELETE CASCADE, 
	CONSTRAINT fk_store_aliases_retailer_id_retailers FOREIGN KEY(retailer_id) REFERENCES retailers (id) ON DELETE CASCADE
);""",
    r"""CREATE TABLE validation_issues (
	id UUID DEFAULT uuidv7() NOT NULL, 
	source_file_id UUID NOT NULL, 
	ingestion_run_id UUID, 
	replay_run_id UUID, 
	severity VARCHAR(32) NOT NULL, 
	code VARCHAR(128) NOT NULL, 
	message TEXT NOT NULL, 
	record_index BIGINT, 
	field_name VARCHAR(256), 
	rejected_value TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT clock_timestamp() NOT NULL, 
	CONSTRAINT pk_validation_issues PRIMARY KEY (id), 
	CONSTRAINT ck_validation_issues_severity_value CHECK (severity IN ('warning', 'record_rejection', 'file_quarantine', 'source_failure', 'system_failure')), 
	CONSTRAINT ck_validation_issues_code_length CHECK (length(code) BETWEEN 1 AND 128), 
	CONSTRAINT ck_validation_issues_exactly_one_run CHECK (num_nonnulls(ingestion_run_id, replay_run_id) = 1), 
	CONSTRAINT fk_validation_issues_source_file_id_source_files FOREIGN KEY(source_file_id) REFERENCES source_files (id) ON DELETE CASCADE, 
	CONSTRAINT fk_validation_issues_ingestion_run_id_ingestion_runs FOREIGN KEY(ingestion_run_id) REFERENCES ingestion_runs (id) ON DELETE CASCADE, 
	CONSTRAINT fk_validation_issues_replay_run_id_replay_runs FOREIGN KEY(replay_run_id) REFERENCES replay_runs (id) ON DELETE CASCADE
);""",
    r"""CREATE INDEX ix_canonical_products_name_search_trgm ON canonical_products USING gin (name_search gin_trgm_ops);""",
    r"""CREATE INDEX ix_leases_expiry ON leases (expires_at);""",
    r"""CREATE INDEX ix_portals_source_key ON portals (source_key);""",
    r"""CREATE INDEX ix_product_identifiers_product ON product_identifiers (product_id);""",
    r"""CREATE UNIQUE INDEX uq_product_identifiers_identity ON product_identifiers (kind, normalized_value, issuer_retailer_id) NULLS NOT DISTINCT;""",
    r"""CREATE INDEX ix_source_files_archive_object ON source_files (raw_archive_object_id);""",
    r"""CREATE INDEX ix_source_files_retailer_document_source_time ON source_files (retailer_id, document_type, source_timestamp DESC);""",
    r"""CREATE INDEX ix_source_files_status_discovered_id ON source_files (status, discovered_at, id);""",
    r"""CREATE INDEX ix_ingestion_runs_source_file_started ON ingestion_runs (source_file_id, started_at DESC);""",
    r"""CREATE INDEX ix_promotions_active_window ON promotions (starts_at, ends_at, id) WHERE valid_to IS NULL;""",
    r"""CREATE UNIQUE INDEX uq_promotions_open ON promotions (retailer_id, source_promotion_id, source_scope_store_code) WHERE valid_to IS NULL;""",
    r"""CREATE INDEX ix_replay_runs_source_file_started ON replay_runs (source_file_id, started_at DESC);""",
    r"""CREATE UNIQUE INDEX uq_replay_runs_open_source_file ON replay_runs (source_file_id) WHERE finished_at IS NULL;""",
    r"""CREATE INDEX ix_retailer_items_gtin ON retailer_items (gtin);""",
    r"""CREATE INDEX ix_retailer_items_name_search_trgm ON retailer_items USING gin (name_search gin_trgm_ops);""",
    r"""CREATE INDEX ix_staged_prices_file_store_item_record ON staged_prices (source_file_id, subchain_id, source_store_id, source_item_code, record_index DESC);""",
    r"""CREATE INDEX ix_staged_promotions_file_identity_record ON staged_promotions (source_file_id, source_promotion_id, source_scope_store_code, record_index DESC);""",
    r"""CREATE INDEX ix_staged_stores_file_identity ON staged_stores (source_file_id, subchain_id, source_store_id);""",
    r"""CREATE INDEX ix_stores_name_search_trgm ON stores USING gin (name_search gin_trgm_ops);""",
    r"""CREATE INDEX ix_stores_retailer_city_id ON stores (retailer_id, city, id);""",
    r"""CREATE INDEX ix_availability_history_item_store_from ON availability_history (retailer_item_id, store_id, valid_from DESC, id);""",
    r"""CREATE UNIQUE INDEX uq_availability_history_open ON availability_history (retailer_item_id, store_id) WHERE valid_to IS NULL;""",
    r"""CREATE INDEX ix_confirmed_product_matches_product_item ON confirmed_product_matches (canonical_product_id, retailer_item_id);""",
    r"""CREATE INDEX ix_current_availability_store_available_item ON current_availability (store_id, is_available, retailer_item_id);""",
    r"""CREATE INDEX ix_current_prices_store_price_item ON current_prices (store_id, item_price, retailer_item_id);""",
    r"""CREATE INDEX ix_price_history_item_store_from ON price_history (retailer_item_id, store_id, valid_from DESC, id);""",
    r"""CREATE UNIQUE INDEX uq_price_history_open ON price_history (retailer_item_id, store_id) WHERE valid_to IS NULL;""",
    r"""CREATE INDEX ix_match_candidates_status_score ON product_match_candidates (status, score DESC, id);""",
    r"""CREATE INDEX ix_promotion_items_item_promotion ON promotion_items (retailer_item_id, promotion_id);""",
    r"""CREATE INDEX ix_promotion_stores_store_promotion ON promotion_stores (store_id, promotion_id);""",
    r"""CREATE INDEX ix_source_file_events_file_time ON source_file_events (source_file_id, occurred_at, id);""",
    r"""CREATE INDEX ix_validation_issues_file_severity_record ON validation_issues (source_file_id, severity, record_index);""",
)

TABLES_IN_DROP_ORDER: tuple[str, ...] = (
    "validation_issues",
    "store_aliases",
    "staged_promotion_stores",
    "staged_promotion_items",
    "staged_promotion_clubs",
    "source_file_events",
    "promotion_stores",
    "promotion_items",
    "promotion_clubs",
    "product_match_candidates",
    "price_history",
    "current_prices",
    "current_availability",
    "confirmed_product_matches",
    "availability_history",
    "stores",
    "staged_stores",
    "staged_promotions",
    "staged_prices",
    "staged_documents",
    "retailer_items",
    "replay_runs",
    "promotions",
    "ingestion_runs",
    "applied_source_contents",
    "source_files",
    "product_identifiers",
    "portals",
    "retailers",
    "raw_archive_objects",
    "leases",
    "canonical_products",
)


def upgrade() -> None:
    for statement in SCHEMA_DDL:
        op.execute(statement)


def downgrade() -> None:
    for table_name in TABLES_IN_DROP_ORDER:
        op.execute(f'DROP TABLE IF EXISTS "{table_name}"')
